// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntoVenta.Infrastructure.Persistence;

#nullable disable

namespace PuntoVenta.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612205923_PodaFina_Secuencias_CajaActivo")]
    partial class PodaFina_Secuencias_CajaActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Cajas.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoNormalizado")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasFilter("\"Identificacion\" IS NOT NULL");

                    b.HasIndex("NombreNormalizado");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.CodigosImpuesto.CodigoImpuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("CodigosImpuesto", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.CondicionesVenta.CondicionVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("CondicionesVenta", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Impresion.PerfilImpresoraTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("AnchoMm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharsPorLinea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codepage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComandoCorte")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Densidad")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DrawerPin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("PerfilesImpresoraTicket", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.MediosPago.MedioPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("MediosPago", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Negocios.Negocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicaCajas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("AplicaVendedores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Correo")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Negocios", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Negocios.NegocioTicketConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AplicaCopiaClienteNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensajePie")
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MostrarCodigoBarras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("MostrarLogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("NegocioTicketConfigs", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Paginas.Pagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PaginaPadreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaginaPadreId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Paginas", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Paginas.PaginaPermiso", b =>
                {
                    b.Property<Guid>("PaginaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("TEXT");

                    b.HasKey("PaginaId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("PaginaPermisos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Permisos.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.HasIndex("Modulo");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Productos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoAplicaExistencias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermiteModificarPrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("TarifaIvaImpuestoCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoItem")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CodigoBarras")
                        .IsUnique()
                        .HasFilter("\"CodigoBarras\" IS NOT NULL");

                    b.HasIndex("Nombre");

                    b.HasIndex("TarifaIvaImpuestoCodigo");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Roles.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Secuencias.Secuencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumento")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Secuencias", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.TarifasIvaImpuesto.TarifaIvaImpuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("TarifasIvaImpuesto", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.TiposIdentificacion.TipoIdentificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("TiposIdentificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Tokens.RefreshTokenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreadoPorIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiracionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReemplazadoPorTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevocadoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoUsoEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoUsoPorIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "ExpiracionUtc");

                    b.ToTable("RefreshTokenSessions", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Tokens.TokenRevocado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRevocacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaExpiracion");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("TokensRevocados", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DebeCambiarPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordTemporalExpiraEnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Vendedores.Vendedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Vendedores", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CajaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionVentaCodigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionVentaDetalleSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Consecutivo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentoOrigenId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NumeroConsecutivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlazoCreditoDias")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalComprobante")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalImpuesto")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalMercanciasExentas")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalMercanciasGravadas")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalServiciosExentos")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalServiciosGravados")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("TotalVenta")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DocumentoOrigenId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("Estado", "FechaDocumento");

                    b.HasIndex("TipoDocumento", "CajaId", "NumeroConsecutivo")
                        .IsUnique();

                    b.ToTable("DocumentosVenta", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CorrelacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoVentaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcurridoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEventoCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TipoEventoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoEventoId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.HasIndex("DocumentoVentaId", "OcurridoEn");

                    b.HasIndex("TipoEventoCodigo", "OcurridoEn");

                    b.ToTable("DocumentosVentaEventos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DevuelveInventario")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DocumentoVentaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("decimal(18,5)");

                    b.Property<bool>("NoAplicaExistencias")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermiteModificarPrecioUnitario")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,5)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("TarifaIvaImpuestoCodigo")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoItem")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("UnidadMedidaCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoVentaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DocumentosVentaLineas", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveHaciendaREP")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsecutivoHaciendaREP")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoVentaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoElectronicoREP")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAceptacionREP")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedioPagoCodigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MedioPagoDetalleSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoAplicadoDocumento")
                        .HasColumnType("numeric(18,5)");

                    b.Property<decimal>("MontoAplicadoMonedaPago")
                        .HasColumnType("numeric(18,5)");

                    b.Property<decimal>("MontoEntregado")
                        .HasColumnType("numeric(18,5)");

                    b.Property<decimal>("MontoVueltoDocumento")
                        .HasColumnType("numeric(18,5)");

                    b.Property<decimal>("MontoVueltoMonedaPago")
                        .HasColumnType("numeric(18,5)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TipoCambioAplicado")
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("UsuarioRegistroId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoVentaId");

                    b.HasIndex("UsuarioRegistroId");

                    b.ToTable("DocumentosVentaPagos", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaReferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoRazon")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoReferenciaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentoVentaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDocumentoReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocReferencia")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoReferenciaId");

                    b.HasIndex("DocumentoVentaId");

                    b.ToTable("DocumentosVentaReferencias", (string)null);
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.TipoDocumentoVentaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorSugerido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconoSugerido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("TipoDocumentoVentaEvento");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Cajas.Caja", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Categorias.Categoria", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Clientes.Cliente", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.CodigosImpuesto.CodigoImpuesto", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.CondicionesVenta.CondicionVenta", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Impresion.PerfilImpresoraTicket", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.MediosPago.MedioPago", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Negocios.Negocio", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Negocios.NegocioTicketConfig", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("PuntoVenta.Domain.Entities.Negocios.ConfiguracionPieDocumento", "Configuraciones", b1 =>
                        {
                            b1.Property<Guid>("NegocioTicketConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Destino");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(60);

                            b1.PrimitiveCollection<string>("TiposDocumento")
                                .IsRequired();

                            b1.HasKey("NegocioTicketConfigId", "__synthesizedOrdinal");

                            b1.ToTable("NegocioTicketConfigs");

                            b1
                                .ToJson("Configuraciones")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("NegocioTicketConfigId");

                            b1.OwnsMany("PuntoVenta.Domain.Entities.Negocios.LineaPieDocumento", "Lineas", b2 =>
                                {
                                    b2.Property<Guid>("ConfiguracionPieDocumentoNegocioTicketConfigId");

                                    b2.Property<int>("ConfiguracionPieDocumento__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<int>("Alineacion");

                                    b2.Property<bool>("Negrita");

                                    b2.Property<int>("Orden");

                                    b2.Property<string>("Texto")
                                        .IsRequired()
                                        .HasMaxLength(120);

                                    b2.HasKey("ConfiguracionPieDocumentoNegocioTicketConfigId", "ConfiguracionPieDocumento__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("NegocioTicketConfigs");

                                    b2.WithOwner()
                                        .HasForeignKey("ConfiguracionPieDocumentoNegocioTicketConfigId", "ConfiguracionPieDocumento__synthesizedOrdinal");
                                });

                            b1.Navigation("Lineas");
                        });

                    b.OwnsMany("PuntoVenta.Domain.Entities.Negocios.ElementoEncabezado", "ElementosEncabezado", b1 =>
                        {
                            b1.Property<Guid>("NegocioTicketConfigId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Orden");

                            b1.Property<string>("TextoLibre")
                                .HasMaxLength(60);

                            b1.Property<int>("Tipo");

                            b1.Property<bool>("Visible");

                            b1.HasKey("NegocioTicketConfigId", "__synthesizedOrdinal");

                            b1.ToTable("NegocioTicketConfigs");

                            b1
                                .ToJson("ElementosEncabezado")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("NegocioTicketConfigId");
                        });

                    b.Navigation("Configuraciones");

                    b.Navigation("ElementosEncabezado");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Paginas.Pagina", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Paginas.Pagina", "PaginaPadre")
                        .WithMany()
                        .HasForeignKey("PaginaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PaginaPadre");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Paginas.PaginaPermiso", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Paginas.Pagina", "Pagina")
                        .WithMany("PaginaPermisos")
                        .HasForeignKey("PaginaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Permisos.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagina");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Permisos.Permiso", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Productos.Producto", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.TarifasIvaImpuesto.TarifaIvaImpuesto", null)
                        .WithMany()
                        .HasForeignKey("TarifaIvaImpuestoCodigo")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Roles.Rol", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Roles.RolPermiso", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Permisos.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Roles.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Secuencias.Secuencia", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.TarifasIvaImpuesto.TarifaIvaImpuesto", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.TiposIdentificacion.TipoIdentificacion", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId");

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Vendedores.Vendedor", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Cajas.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("CajaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoOrigen")
                        .WithMany()
                        .HasForeignKey("DocumentoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Vendedores.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caja");

                    b.Navigation("Cliente");

                    b.Navigation("DocumentoOrigen");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaEvento", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoVenta")
                        .WithMany()
                        .HasForeignKey("DocumentoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.TipoDocumentoVentaEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("TipoEventoId");

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentoVenta");

                    b.Navigation("TipoEvento");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaLinea", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoVenta")
                        .WithMany("Lineas")
                        .HasForeignKey("DocumentoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentoVenta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaPago", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoVenta")
                        .WithMany("Pagos")
                        .HasForeignKey("DocumentoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocumentoVenta");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVentaReferencia", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoReferencia")
                        .WithMany()
                        .HasForeignKey("DocumentoReferenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", "DocumentoVenta")
                        .WithMany("Referencias")
                        .HasForeignKey("DocumentoVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoReferencia");

                    b.Navigation("DocumentoVenta");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.TipoDocumentoVentaEvento", b =>
                {
                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId");

                    b.HasOne("PuntoVenta.Domain.Entities.Usuarios.Usuario", "UsuarioModificacion")
                        .WithMany()
                        .HasForeignKey("UsuarioModificacionId");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Paginas.Pagina", b =>
                {
                    b.Navigation("PaginaPermisos");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Permisos.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Roles.Rol", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("PuntoVenta.Domain.Entities.Ventas.DocumentoVenta", b =>
                {
                    b.Navigation("Lineas");

                    b.Navigation("Pagos");

                    b.Navigation("Referencias");
                });
#pragma warning restore 612, 618
        }
    }
}
