import type { BreadcrumbRoute } from "@lib/utils/routes.utils";

export const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    CAMBIAR_PASSWORD: "/cambiar-password",
    MI_PERFIL: "/mi-perfil",
    API_LOGOUT: "/api/auth/clear-session",
    API_VALIDATE_PERMISSION: "/api/auth/validate-permission",
    API_VALIDATE_SESSION: "/api/auth/validate-session",
    SISTEMA: "/sistema",
    CATALOGOS: "/sistema/catalogos",
    MI_NEGOCIO: "/sistema/mi-negocio",
    MANTENIMIENTO_CATEGORIAS: "/mantenimiento/categorias",
    MANTENIMIENTO_VENDEDORES: "/mantenimiento/vendedores",
    INVENTARIO_PRODUCTOS: "/inventario/productos",
    INVENTARIO_MOVIMIENTOS: "/inventario/movimientos",
    EMISION: "/emision",
    EMISION_VENTAS: "/emision/ventas",
    EMISION_FACTURACION: "/emision/facturacion",
    EMISION_COBROS: "/emision/cobros",
    EMISION_COBROS_CREDITO: "/emision/cobros/credito",
    CLIENTES: "/clientes",
    REPORTES: "/reportes-ventas",
    REPORTES_MOVIMIENTOS_DINERO: "/reportes-ventas/movimientos-dinero",
    REPORTES_VENTAS_RANGO: "/reportes-ventas/ventas-rango",
    PERMISO_DENEGADO: "/permiso-denegado",
    ROLES: "/sistema/roles",
    USUARIOS: "/sistema/usuarios",
    CAJAS: "/sistema/cajas",
    RESPALDO: "/sistema/respaldo",
    ACERCA: "/acerca",
} as const;

export const BREADCRUMB_ROUTES: readonly BreadcrumbRoute[] = [
    { pattern: "/sistema", label: "Sistema", href: null, title_page: "Sistema" },
    { pattern: "/sistema/catalogos", label: "Catálogos", href: "/sistema/catalogos", title_page: "Catálogos" },
    { pattern: "/sistema/mi-negocio", label: "Mi Negocio", href: "/sistema/mi-negocio", title_page: "Mi Negocio" },
    { pattern: "/inventario", label: "Inventario", href: null, title_page: "Inventario" },
    { pattern: "/inventario/productos", label: "Productos", href: "/inventario/productos", title_page: "Productos" },
    { pattern: "/inventario/movimientos", label: "Movimientos", href: "/inventario/movimientos", title_page: "Movimientos" },
    { pattern: "/inventario/productos/nuevo", label: "Nuevo", href: null, title_page: "Nuevo producto" },
    { pattern: "/inventario/productos/*/editar", label: "Editar", href: null, title_page: "Editar producto" },
    { pattern: "/inventario/productos/*", label: "Detalle", href: null, title_page: "Detalle de producto" },
    { pattern: "/emision", label: "Emisión", href: null, title_page: "Emisión" },
    { pattern: "/emision/facturacion", label: "Facturación", href: "/emision/facturacion", title_page: "Facturación" },
    { pattern: "/emision/ventas", label: "Ventas", href: "/emision/ventas", title_page: "Ventas" },
    { pattern: "/emision/ventas/*", label: "Detalle", href: null, title_page: "Detalle de venta" },
    { pattern: "/emision/cobros", label: "Cobros", href: null, title_page: "Cobros" },
    { pattern: "/emision/cobros/credito", label: "Créditos", href: "/emision/cobros/credito", title_page: "Créditos" },
    { pattern: "/clientes", label: "Clientes", href: "/clientes", title_page: "Clientes" },
    { pattern: "/reportes-ventas", label: "Reportes Ventas", href: "/reportes-ventas", title_page: "Reportes Ventas" },
    { pattern: "/reportes-ventas/movimientos-dinero", label: "Movimientos de dinero", href: null, title_page: "Movimientos de dinero" },
    { pattern: "/reportes-ventas/ventas-rango", label: "Ventas por rango", href: null, title_page: "Reporte de ventas por rango" },
    { pattern: "/mantenimiento", label: "Mantenimiento", href: null, title_page: "Mantenimiento" },
    { pattern: "/mantenimiento/categorias", label: "Categorías", href: "/mantenimiento/categorias", title_page: "Categorías" },
    { pattern: "/mantenimiento/vendedores", label: "Vendedores", href: "/mantenimiento/vendedores", title_page: "Vendedores" },
    { pattern: "/sistema/usuarios", label: "Usuarios", href: "/sistema/usuarios", title_page: "Usuarios" },
    { pattern: "/sistema/cajas", label: "Cajas", href: "/sistema/cajas", title_page: "Cajas" },
    { pattern: "/sistema/usuarios/*/detalle", label: "Detalle", href: null, title_page: "Detalle de usuario" },
    { pattern: "/mi-perfil", label: "Mi perfil", href: null, title_page: "Mi perfil" },
    { pattern: "/sistema/roles", label: "Roles", href: "/sistema/roles", title_page: "Roles" },
    { pattern: "/sistema/roles/*/permisos", label: "Permisos", href: null, title_page: "Permisos de rol" },
    { pattern: "/sistema/respaldo", label: "Respaldo", href: "/sistema/respaldo", title_page: "Respaldo de base de datos" },
    { pattern: "/permiso-denegado", label: "Permiso denegado", href: null, title_page: "Permiso denegado" },
    { pattern: "/acerca", label: "Acerca de", href: null, title_page: "Acerca de" },
] as const;
